// <auto-generated />
// Generated by tools/KnownModelsGenerator from ModelPriceCatalog.Default. Do not edit manually.

namespace TokenEconomy;

/// <summary>Strongly typed canonical model ids from the default price catalog.</summary>
public static class KnownModels
{
    /// <summary>The canonical <c>claude-fable-5</c> model id.</summary>
    public static readonly ModelId ClaudeFable5 = ModelId.Of("claude-fable-5");

    /// <summary>The canonical <c>claude-mythos-5</c> model id.</summary>
    public static readonly ModelId ClaudeMythos5 = ModelId.Of("claude-mythos-5");

    /// <summary>The canonical <c>claude-opus-5</c> model id.</summary>
    public static readonly ModelId ClaudeOpus5 = ModelId.Of("claude-opus-5");

    /// <summary>The canonical <c>claude-sonnet-5</c> model id.</summary>
    public static readonly ModelId ClaudeSonnet5 = ModelId.Of("claude-sonnet-5");

    /// <summary>The canonical <c>claude-opus-4-8</c> model id.</summary>
    public static readonly ModelId ClaudeOpus48 = ModelId.Of("claude-opus-4-8");

    /// <summary>The canonical <c>claude-opus-4-7</c> model id.</summary>
    public static readonly ModelId ClaudeOpus47 = ModelId.Of("claude-opus-4-7");

    /// <summary>The canonical <c>claude-opus-4-6</c> model id.</summary>
    public static readonly ModelId ClaudeOpus46 = ModelId.Of("claude-opus-4-6");

    /// <summary>The canonical <c>claude-opus-4-5</c> model id.</summary>
    public static readonly ModelId ClaudeOpus45 = ModelId.Of("claude-opus-4-5");

    /// <summary>The canonical <c>claude-opus-4-1</c> model id.</summary>
    public static readonly ModelId ClaudeOpus41 = ModelId.Of("claude-opus-4-1");

    /// <summary>The canonical <c>claude-sonnet-4-6</c> model id.</summary>
    public static readonly ModelId ClaudeSonnet46 = ModelId.Of("claude-sonnet-4-6");

    /// <summary>The canonical <c>claude-sonnet-4-5</c> model id.</summary>
    public static readonly ModelId ClaudeSonnet45 = ModelId.Of("claude-sonnet-4-5");

    /// <summary>The canonical <c>claude-haiku-4-5</c> model id.</summary>
    public static readonly ModelId ClaudeHaiku45 = ModelId.Of("claude-haiku-4-5");

    /// <summary>The canonical <c>gpt-5.6-luna</c> model id.</summary>
    public static readonly ModelId Gpt56Luna = ModelId.Of("gpt-5.6-luna");

    /// <summary>The canonical <c>gpt-5.6-terra</c> model id.</summary>
    public static readonly ModelId Gpt56Terra = ModelId.Of("gpt-5.6-terra");

    /// <summary>The canonical <c>gpt-5.6-sol</c> model id.</summary>
    public static readonly ModelId Gpt56Sol = ModelId.Of("gpt-5.6-sol");

    /// <summary>The canonical <c>gpt-5.4-mini</c> model id.</summary>
    public static readonly ModelId Gpt54Mini = ModelId.Of("gpt-5.4-mini");

    /// <summary>The canonical <c>gpt-5.5</c> model id.</summary>
    public static readonly ModelId Gpt55 = ModelId.Of("gpt-5.5");

    /// <summary>The canonical <c>gpt-5</c> model id.</summary>
    public static readonly ModelId Gpt5 = ModelId.Of("gpt-5");

    /// <summary>The canonical <c>gpt-5-codex</c> model id.</summary>
    public static readonly ModelId Gpt5Codex = ModelId.Of("gpt-5-codex");

}
