using System.Text;
using System.Globalization;

namespace TokenEconomy;

/// <summary>Deterministic public Markdown projection of the embedded routing knowledge base.</summary>
public static class ModelRoutingKnowledgeRenderer
{
    /// <summary>Render without wall-clock input; policy and evidence dates come from versioned data.</summary>
    public static string Render(ModelRoutingKnowledgeBase knowledge)
    {
        ArgumentNullException.ThrowIfNull(knowledge);
        var output = new StringBuilder();
        output.AppendLine("# Model routing knowledge");
        output.AppendLine();
        output.AppendLine("> Generated from `src/TokenEconomy/catalog/model-routing-policy.json` and `results/routing-evidence/review/v1/review-evidence.json`; do not edit this file directly.");
        output.AppendLine();
        output.AppendLine($"Policy version: `{knowledge.PolicyVersion:yyyy-MM-dd}`  ");
        output.AppendLine($"Evidence as of: `{knowledge.EvidenceAsOfDate:yyyy-MM-dd}`  ");
        output.AppendLine($"Authority: `{knowledge.Authority.RepositoryPath}`  ");
        output.AppendLine($"Authority SHA-256: `{knowledge.Authority.ContentSha256}`");
        output.AppendLine($"Review evidence: `{knowledge.ReviewEvidenceVersion}`");
        output.AppendLine();
        output.AppendLine("The Markdown authority defines policy. The versioned JSON is its executable projection. Tests compare the authority hash, policy structure, adjacent catalogs, and this generated view so drift cannot pass unnoticed.");
        output.AppendLine();
        output.AppendLine("## Providers and reasoning vocabulary");
        output.AppendLine();
        output.AppendLine("| Provider | CLI | Evidence |");
        output.AppendLine("| --- | --- | --- |");
        foreach (var provider in knowledge.Providers.OrderBy(provider => provider.Id, StringComparer.Ordinal))
            output.AppendLine($"| `{provider.Id}` | `{provider.CliId}` ({provider.CliLabel}) | `{Camel(provider.EvidenceStatus)}` |");
        output.AppendLine();
        output.AppendLine("| Thinking level | Rank | Evidence |");
        output.AppendLine("| --- | ---: | --- |");
        foreach (var level in knowledge.ThinkingLevels.OrderBy(level => level.Rank).ThenBy(level => level.Id, StringComparer.Ordinal))
            output.AppendLine($"| `{level.Id}` | {level.Rank} | `{Camel(level.EvidenceStatus)}` |");
        output.AppendLine();
        output.AppendLine("Supported reasoning is resolved per concrete model. A vocabulary entry does not imply that every model accepts it, and unsupported values are never silently clamped by the routing policy.");
        output.AppendLine();
        output.AppendLine("## Policy routes");
        output.AppendLine();
        output.AppendLine("| Route | Workflow | Score | Canonical model | Thinking | Evidence |");
        output.AppendLine("| --- | --- | ---: | --- | --- | --- |");
        foreach (var route in knowledge.Routes.OrderBy(route => route.WorkflowRole).ThenBy(route => route.Rank).ThenBy(route => route.Id, StringComparer.Ordinal))
        {
            var score = route.MinimumScore is null ? "role exception" : $"{route.MinimumScore}-{route.MaximumScore}";
            output.AppendLine($"| `{route.Id}` | `{Camel(route.WorkflowRole)}` | {score} | `{route.ModelId}` | `{route.ThinkingLevel}` | `{Camel(route.EvidenceStatus)}` |");
        }

        output.AppendLine();
        output.AppendLine("### Weighted score criteria");
        output.AppendLine();
        output.AppendLine("| Criterion | Maximum points |");
        output.AppendLine("| --- | ---: |");
        foreach (var criterion in knowledge.ScoringCriteria)
            output.AppendLine($"| `{criterion.Id}` | {criterion.MaximumPoints} |");

        output.AppendLine();
        output.AppendLine("### Capability and workflow constraints");
        output.AppendLine();
        output.AppendLine("| Route | Use for | Do not use for |");
        output.AppendLine("| --- | --- | --- |");
        foreach (var route in knowledge.Routes.OrderBy(route => route.WorkflowRole).ThenBy(route => route.Rank).ThenBy(route => route.Id, StringComparer.Ordinal))
            output.AppendLine($"| `{route.Id}` | {string.Join(", ", route.UseFor.Select(value => $"`{value}`"))} | {string.Join(", ", route.DoNotUseFor.Select(value => $"`{value}`"))} |");

        output.AppendLine();
        output.AppendLine("## Provider fallbacks");
        output.AppendLine();
        output.AppendLine("| Fallback | Replaces routes | Never substitutes | Model / thinking | Evidence |");
        output.AppendLine("| --- | --- | --- | --- | --- |");
        foreach (var fallback in knowledge.ProviderFallbacks.OrderBy(fallback => fallback.Id, StringComparer.Ordinal))
            output.AppendLine($"| `{fallback.Id}` | {string.Join(", ", fallback.ForRouteIds.Select(route => $"`{route}`"))} | {string.Join(", ", fallback.NotForRouteIds.Select(route => $"`{route}`"))} | `{fallback.ModelId}` / `{fallback.ThinkingLevel}` | `{Camel(fallback.EvidenceStatus)}` |");

        output.AppendLine();
        output.AppendLine("## Models and canonical resolution");
        output.AppendLine();
        output.AppendLine("| Canonical model | Aliases | Provider / CLI | Thinking levels | Routing status | Evidence | Review quality | Review evidence | Catalog links |");
        output.AppendLine("| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
        foreach (var model in knowledge.Models.OrderBy(model => model.CanonicalId, StringComparer.Ordinal))
        {
            var aliases = model.Aliases.Count == 0 ? "—" : string.Join(", ", model.Aliases.Select(alias => $"`{alias}`"));
            var levels = string.Join(", ", model.SupportedThinkingLevels.Select(level => $"`{level}`"));
            var review = knowledge.ReviewQualityFor(model.CanonicalId);
            var reviewQuality = review?.Suitability is { } suitability ? $"`{Camel(suitability)}`" : "insufficient evidence";
            var reviewEvidence = review is null ? "`unknown` / `insufficientEvidence`" : $"`{Camel(review.EvidenceStatus)}` / `{Camel(review.EvidenceQuality)}`";
            output.AppendLine($"| `{model.CanonicalId}` | {aliases} | `{model.ProviderId}` / `{model.CliId}` | {levels} | `{Camel(model.RoutingStatus)}` | `{Camel(model.EvidenceStatus)}` | {reviewQuality} | {reviewEvidence} | price `{model.PriceCatalogId}`; media `{model.MediaCatalogModelId}`; trust `{model.TrustModelId}` |");
        }

        output.AppendLine();
        output.AppendLine("## Review quality (Quality Studio)");
        output.AppendLine();
        output.AppendLine("| Model | Quality signal | Runs | Files | Findings | Confirmed / dismissed | Finding outcome coverage | Thinking / aspects | Evidence status / quality |");
        output.AppendLine("| --- | --- | ---: | ---: | ---: | ---: | ---: | --- | --- |");
        foreach (var review in knowledge.ReviewQuality.OrderBy(review => review.CanonicalModel, StringComparer.Ordinal))
        {
            var quality = review.Suitability is { } suitability ? $"`{Camel(suitability)}`" : "insufficient evidence";
            var outcomes = review.AssessedFindingCount == 0 ? "—" : $"{review.ConfirmedFindings} / {review.DismissedFindings}";
            var coverage = Percent(review.FindingOutcomeCoverage);
            var dimensions = review.ThinkingLevels.Count == 0
                ? "—"
                : $"{string.Join(", ", review.ThinkingLevels.Select(value => $"`{value}`"))} / {string.Join(", ", review.ReviewAspects.Select(value => $"`{value}`"))}";
            output.AppendLine($"| `{review.CanonicalModel}` | {quality} | {review.RunCount} | {review.FilesReviewed} | {review.FindingsReported} | {outcomes} | {coverage} | {dimensions} | `{Camel(review.EvidenceStatus)}` / `{Camel(review.EvidenceQuality)}` |");
        }
        output.AppendLine();
        output.AppendLine("Quality Studio history is observational operational evidence, not a controlled A/B comparison. A finding confirmation rate is a precision signal over sighted findings; it does not measure missed findings or recall. Fixture runs validate only the ingestion contract and never contribute to model metrics. Until the declared run, assessed-finding, and outcome-coverage gates pass, the matrix retains a null review suitability and `SuggestModel(review, ...)` returns no candidate rather than inventing a fit.");

        output.AppendLine();
        output.AppendLine("## Hard correctness floors");
        output.AppendLine();
        output.AppendLine("| Floor | Triggers | Minimum route |");
        output.AppendLine("| --- | --- | --- |");
        foreach (var floor in knowledge.HardFloors)
            output.AppendLine($"| `{floor.Id}` | {string.Join(", ", floor.Triggers.Select(trigger => $"`{trigger}`"))} | `{floor.MinimumRouteId}` |");

        output.AppendLine();
        output.AppendLine("Price and quota may rank equivalent available routes or contribute only the declared 0-5 intake points. They never lower a hard correctness floor. Unknown prices, missing trust denominators, unverified media costs, unsupported model/level pairs, restrictions, deprecations, and provisional evidence remain explicit.");
        output.AppendLine();
        output.AppendLine($"Trust reconciliation: named models are `{knowledge.CatalogContracts.NamedModelTrustEvidenceStatus}`; recovered historical incidents remain attributed to `{knowledge.CatalogContracts.HistoricalIncidentAttribution}`. Neither state is converted to a zero violation rate or provider ranking.");
        output.AppendLine();
        output.AppendLine("## Reissue rule");
        output.AppendLine();
        output.AppendLine($"Semantic reissues and substantive C/D reviews set empirical confidence to `{knowledge.ReissueRules.EmpiricalConfidencePointsAfterSemanticFailure}` and raise the next attempt by at least `{knowledge.ReissueRules.MinimumCoreTierIncrease}` core tier. The do-not-promote outcomes are {string.Join(", ", knowledge.ReissueRules.DoNotPromoteOn.Select(value => $"`{value}`"))}. After `{knowledge.ReissueRules.StopAfterSemanticFailuresAtStrongerTier}` semantic failures at the stronger tier, escalation stops for task narrowing, better evidence, or a human decision.");
        return output.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static string Camel<T>(T value) where T : struct, Enum
    {
        var text = value.ToString();
        return char.ToLowerInvariant(text[0]) + text[1..];
    }

    private static string Percent(decimal? value)
        => value is null ? "—" : value.Value.ToString("P1", CultureInfo.InvariantCulture);
}
