using System.Text;

namespace TokenEconomy.Tools;

/// <summary>Renders the checked-in typed constants for canonical model catalog ids.</summary>
public static class KnownModelsSourceGenerator
{
    /// <summary>Render one <c>KnownModels</c> field per canonical model id, preserving input order.</summary>
    public static string Render(IEnumerable<string> canonicalModelIds)
    {
        ArgumentNullException.ThrowIfNull(canonicalModelIds);

        var models = canonicalModelIds.Select(modelId => new ModelConstant(modelId, ToPascalName(modelId))).ToArray();
        var names = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var model in models)
        {
            if (names.TryGetValue(model.Name, out var existing))
                throw new ArgumentException(
                    $"Canonical model ids '{existing}' and '{model.ModelId}' both generate KnownModels.{model.Name}.",
                    nameof(canonicalModelIds));
            names.Add(model.Name, model.ModelId);
        }

        var output = new StringBuilder();
        output.Append("// <auto-generated />\n");
        output.Append("// Generated by tools/KnownModelsGenerator from ModelPriceCatalog.Default. Do not edit manually.\n\n");
        output.Append("namespace TokenEconomy;\n\n");
        output.Append("/// <summary>Strongly typed canonical model ids from the default price catalog.</summary>\n");
        output.Append("public static class KnownModels\n");
        output.Append("{\n");
        foreach (var model in models)
        {
            output.Append("    /// <summary>The canonical <c>");
            output.Append(model.ModelId);
            output.Append("</c> model id.</summary>\n");
            output.Append("    public static readonly ModelId ");
            output.Append(model.Name);
            output.Append(" = ModelId.Of(\"");
            output.Append(EscapeString(model.ModelId));
            output.Append("\");\n\n");
        }
        output.Append("}\n");
        return output.ToString();
    }

    /// <summary>
    /// Convert a canonical id to a member name by splitting on dashes and dots, lowercasing each
    /// segment, and capitalizing its first character.
    /// </summary>
    public static string ToPascalName(string modelId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(modelId);
        var segments = modelId.Split(['-', '.'], StringSplitOptions.RemoveEmptyEntries);
        if (segments.Length == 0 || segments.Any(segment => segment.Any(character => !char.IsAsciiLetterOrDigit(character))))
            throw new ArgumentException($"Model id '{modelId}' cannot be converted to a KnownModels member name.", nameof(modelId));

        var output = new StringBuilder(modelId.Length);
        foreach (var segment in segments)
        {
            var lower = segment.ToLowerInvariant();
            output.Append(char.ToUpperInvariant(lower[0]));
            output.Append(lower.AsSpan(1));
        }

        if (!char.IsAsciiLetter(output[0]))
            throw new ArgumentException($"Model id '{modelId}' does not generate a valid C# member name.", nameof(modelId));
        return output.ToString();
    }

    private static string EscapeString(string value)
        => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);

    private sealed record ModelConstant(string ModelId, string Name);
}
